cmake_minimum_required(VERSION 3.20)
foreach(report IN ITEMS coverage.xml coverage.html)
    if(NOT EXISTS "${TOOLX_COVERAGE_DIR}/${report}")
        message(FATAL_ERROR "Missing coverage artifact: ${report}")
    endif()
    file(SIZE "${TOOLX_COVERAGE_DIR}/${report}" size)
    if(size EQUAL 0)
        message(FATAL_ERROR "Empty coverage artifact: ${report}")
    endif()
endforeach()
file(READ "${TOOLX_COVERAGE_DIR}/coverage.xml" xml)
if(NOT xml MATCHES "<coverage " OR NOT xml MATCHES "</coverage>" OR NOT xml MATCHES "filename=\"(src|include)/")
    message(FATAL_ERROR "Coverage XML must contain a complete src/include report")
endif()
string(REGEX MATCHALL "filename=\"[^\"]+\"" filenames "${xml}")
foreach(filename IN LISTS filenames)
    if(NOT filename MATCHES "^filename=\"(src|include)/")
        message(FATAL_ERROR "Unexpected coverage source: ${filename}")
    endif()
endforeach()
file(READ "${TOOLX_COVERAGE_DIR}/coverage.html" html)
if(NOT html MATCHES "</html>")
    message(FATAL_ERROR "Coverage HTML report is incomplete")
endif()
message(STATUS "Coverage artifacts verified")
