cmake_minimum_required(VERSION 3.20)
set(root "${CMAKE_CURRENT_BINARY_DIR}/coverage-report-fixtures")
file(MAKE_DIRECTORY "${root}")
function(check success)
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DTOOLX_COVERAGE_DIR=${root}"
        -P "${CMAKE_CURRENT_LIST_DIR}/coverage_report_check.cmake"
        RESULT_VARIABLE result OUTPUT_QUIET ERROR_QUIET)
    if(success AND NOT result EQUAL 0 OR NOT success AND result EQUAL 0)
        message(FATAL_ERROR "Unexpected coverage artifact validation result: ${result}")
    endif()
endfunction()
file(REMOVE "${root}/coverage.xml" "${root}/coverage.html")
check(FALSE)
file(WRITE "${root}/coverage.xml" "<coverage ><class filename=\"src/fsx.cpp\"/></coverage>")
check(FALSE)
file(WRITE "${root}/coverage.html" "<html></html>")
check(TRUE)
file(WRITE "${root}/coverage.xml" "<coverage ><class filename=\"tests/fsx_tests.cpp\"/></coverage>")
check(FALSE)
file(WRITE "${root}/coverage.xml" "<coverage ><class filename=\"src/fsx.cpp\"/><class filename=\"tests/fsx_tests.cpp\"/></coverage>")
check(FALSE)
file(WRITE "${root}/coverage.xml" "")
check(FALSE)
