cmake_minimum_required(VERSION 3.20)
set(root "${CMAKE_CURRENT_BINARY_DIR}/release-preflight-fixtures")
file(MAKE_DIRECTORY "${root}/docs/releases")
file(WRITE "${root}/README.md" "# ToolX\n> Status: Released\n> Applies to: v0.3.2\n> Latest release: v0.3.2\n")
file(WRITE "${root}/CMakeLists.txt" "project(ToolX VERSION 0.3.2 LANGUAGES CXX)")
file(WRITE "${root}/CHANGELOG.md" "# Changelog\n> Status: Released\n> Applies to: v0.3.2\n## [0.3.2] - 2026-09-06\n")
file(WRITE "${root}/docs/releases/v0.3.2.md" "# ToolX v0.3.2\n> Status: Released\n> Applies to: v0.3.2\n> Source of truth for: release narrative\n")
function(check tag success)
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DTOOLX_SOURCE_ROOT=${root}" "-DTOOLX_RELEASE_TAG=${tag}"
        -P "${CMAKE_CURRENT_LIST_DIR}/release_preflight.cmake" RESULT_VARIABLE result OUTPUT_QUIET ERROR_QUIET)
    if(success AND NOT result EQUAL 0)
        message(FATAL_ERROR "Valid preflight rejected: ${tag}")
    elseif(NOT success AND result EQUAL 0)
        message(FATAL_ERROR "Invalid preflight accepted: ${tag}")
    endif()
endfunction()
check(v0.3.2 TRUE)
check(v0.3.1 FALSE)
check(vanything FALSE)
check(v0.3.2/../../x FALSE)
file(WRITE "${root}/docs/releases/v0.3.2.md" "# ToolX v0.3.20\n> Applies to: v0.3.2\n> Source of truth for: release narrative\n")
check(v0.3.2 FALSE)
file(WRITE "${root}/docs/releases/v0.3.2.md" "# ToolX v0.3.2\n> Status: Released\n> Applies to: v0.3.1\n")
check(v0.3.2 FALSE)
file(WRITE "${root}/docs/releases/v0.3.2.md" "# ToolX v0.3.1\n> Applies to: v0.3.1\n")
check(v0.3.2 FALSE)
file(WRITE "${root}/docs/releases/v0.3.2.md" "# ToolX v0.3.2 Release Candidate\n> Status: Released\n> Applies to: v0.3.2\n> Source of truth for: release narrative\n")
check(v0.3.2 FALSE)
file(WRITE "${root}/docs/releases/v0.3.2.md" "# ToolX v0.3.2 Release Candidate\n> Status: Candidate; not yet tagged\n> Applies to: v0.3.2\n> Source of truth for: release narrative\n")
check(v0.3.2 FALSE)
file(WRITE "${root}/docs/releases/v0.3.2.md" "# ToolX v0.3.2\n> Applies to: v0.3.2\n> Source of truth for: release narrative\n")
check(v0.3.2 FALSE)
file(WRITE "${root}/docs/releases/v0.3.2.md" "# ToolX v0.3.2\n> Status: Released\n> Applies to: v0.3.2\n> Source of truth for: release narrative\n")
foreach(changelog IN ITEMS "## [Unreleased]\nTarget: v0.3.2" "## [0.3.20] - 2026-09-06" "## [0.3.2-preview] - 2026-09-06")
    file(WRITE "${root}/CHANGELOG.md" "${changelog}")
    check(v0.3.2 FALSE)
endforeach()
file(WRITE "${root}/CHANGELOG.md" "# Changelog\n> Status: Released\n> Applies to: v0.3.2\n## [0.3.2] - 2026-09-06\n")
check(v0.3.2 TRUE)
file(REMOVE "${root}/docs/releases/v0.3.2.md")
check(v0.3.2 FALSE)
