cmake_minimum_required(VERSION 3.20)
if(NOT DEFINED TOOLX_SOURCE_ROOT)
    get_filename_component(TOOLX_SOURCE_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()
if(NOT DEFINED TOOLX_RELEASE_TAG)
    set(TOOLX_RELEASE_TAG "$ENV{GITHUB_REF_NAME}")
endif()
if(NOT TOOLX_RELEASE_TAG MATCHES "^v(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$")
    message(FATAL_ERROR "Release tag must be vMAJOR.MINOR.PATCH")
endif()
file(READ "${TOOLX_SOURCE_ROOT}/CMakeLists.txt" project_text)
string(REGEX MATCH "project\\(ToolX VERSION ([0-9]+\\.[0-9]+\\.[0-9]+)" matched "${project_text}")
if(NOT matched OR NOT TOOLX_RELEASE_TAG STREQUAL "v${CMAKE_MATCH_1}")
    message(FATAL_ERROR "Release tag does not match the CMake project version")
endif()
set(notes "${TOOLX_SOURCE_ROOT}/docs/releases/${TOOLX_RELEASE_TAG}.md")
if(NOT EXISTS "${notes}")
    message(FATAL_ERROR "Missing version-specific release notes: ${notes}")
endif()
file(READ "${notes}" notes_text)
string(REGEX MATCH "^# ToolX (v[0-9]+[.][0-9]+[.][0-9]+)([\r\n]|$)" heading "${notes_text}")
if(NOT heading OR NOT CMAKE_MATCH_1 STREQUAL TOOLX_RELEASE_TAG)
    message(FATAL_ERROR "Release note heading does not match the tag")
endif()
# Released documentation has one explicit version/status block per current
# document. Keep this contract here so docs-check and tag publication share it.
function(require_metadata file text field expected)
    string(REGEX MATCHALL "(^|\n)> ${field}:[^\n]*" fields "${text}")
    list(LENGTH fields count)
    if(NOT count EQUAL 1)
        message(FATAL_ERROR "${file}: expected exactly one > ${field}: ${expected}")
    endif()
    string(REGEX REPLACE "^\n" "" actual "${fields}")
    if(NOT actual STREQUAL "> ${field}: ${expected}")
        message(FATAL_ERROR "${file}: expected > ${field}: ${expected}")
    endif()
endfunction()

function(require_final_state file text)
    require_metadata("${file}" "${text}" Status Released)
    require_metadata("${file}" "${text}" "Applies to" "${TOOLX_RELEASE_TAG}")
    string(TOLOWER "${text}" lower)
    # These are reserved release-state markers in the publication scope.
    # Historical CHANGELOG entries are excluded from that scope below.
    if(lower MATCHES "(^|[^a-z])(candidate|unreleased)([^a-z]|$)|not[ \t\n>]+yet[ \t\n>]+tagged|latest[ \t\n>]+tagged[ \t\n>]+release|(^|\n)[ \t>]*target:")
        message(FATAL_ERROR "${file}: residual candidate or stale release-state prose; use the Released metadata contract")
    endif()
endfunction()

foreach(file IN ITEMS README.md CHANGELOG.md)
    if(NOT EXISTS "${TOOLX_SOURCE_ROOT}/${file}")
        message(FATAL_ERROR "Missing release document: ${file}")
    endif()
endforeach()
file(READ "${TOOLX_SOURCE_ROOT}/README.md" readme)
file(READ "${TOOLX_SOURCE_ROOT}/CHANGELOG.md" changelog)
foreach(text IN ITEMS readme changelog notes_text)
    string(REPLACE "\r\n" "\n" ${text} "${${text}}")
endforeach()
require_final_state(README.md "${readme}")
require_metadata(README.md "${readme}" "Latest release" "${TOOLX_RELEASE_TAG}")
require_final_state("docs/releases/${TOOLX_RELEASE_TAG}.md" "${notes_text}")
require_metadata("docs/releases/${TOOLX_RELEASE_TAG}.md" "${notes_text}" "Source of truth for" "release narrative")

string(SUBSTRING "${TOOLX_RELEASE_TAG}" 1 -1 release_version)
string(REPLACE "." "[.]" version_pattern "${release_version}")
string(REGEX MATCH "(^|\n)## [^\n]*" first_heading "${changelog}")
string(STRIP "${first_heading}" first_heading)
if(NOT first_heading MATCHES "^## \\[${version_pattern}\\] - [0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]$")
    message(FATAL_ERROR "CHANGELOG.md: first entry must be ## [${release_version}] - YYYY-MM-DD")
endif()
# Every later H2 must start an older release, so a duplicate current heading
# or an arbitrary section cannot hide current-state prose from validation.
string(REGEX MATCHALL "(^|\n)## [^\n]*" headings "${changelog}")
list(POP_FRONT headings)
foreach(historical_heading IN LISTS headings)
    string(STRIP "${historical_heading}" historical_heading)
    if(NOT historical_heading MATCHES "^## \\[([0-9]+[.][0-9]+[.][0-9]+)\\]([ ]|$)")
        message(FATAL_ERROR "CHANGELOG.md: later H2 headings must identify older releases")
    endif()
    if(NOT CMAKE_MATCH_1 VERSION_LESS release_version)
        message(FATAL_ERROR "CHANGELOG.md: duplicate current or future release entry")
    endif()
endforeach()
# Validate the preamble and current entry; older release history may legitimately
# discuss candidates. Do not let a later historical heading satisfy this gate.
string(FIND "${changelog}" "${first_heading}" heading_at)
string(LENGTH "${first_heading}" heading_length)
math(EXPR after_heading "${heading_at} + ${heading_length}")
string(SUBSTRING "${changelog}" ${after_heading} -1 current_body)
string(FIND "${current_body}" "\n## " next_heading)
if(NOT next_heading EQUAL -1)
    math(EXPR scope_length "${after_heading} + ${next_heading}")
    string(SUBSTRING "${changelog}" 0 ${scope_length} changelog)
endif()
require_final_state(CHANGELOG.md "${changelog}")
message(STATUS "Release preflight passed for ${TOOLX_RELEASE_TAG}")
