cmake_minimum_required(VERSION 3.20)
get_filename_component(source "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(root "${CMAKE_CURRENT_BINARY_DIR}/release-docs-fixture")
file(MAKE_DIRECTORY "${root}")
foreach(item IN ITEMS docs examples include src tools tests cmake .github README.md README.dev.md CHANGELOG.md CMakeLists.txt CMakePresets.json LICENSE)
    file(COPY "${source}/${item}" DESTINATION "${root}")
endforeach()
function(check docs_expected release_expected)
    foreach(mode IN ITEMS docs release)
        if(mode STREQUAL "docs")
            set(script docs_check.cmake)
            set(expected "${docs_expected}")
        else()
            set(script release_preflight.cmake)
            set(expected "${release_expected}")
        endif()
        execute_process(COMMAND "${CMAKE_COMMAND}" "-DTOOLX_REPOSITORY_ROOT=${root}"
            "-DTOOLX_SOURCE_ROOT=${root}" "-DTOOLX_RELEASE_TAG=v0.3.2"
            -P "${CMAKE_CURRENT_LIST_DIR}/${script}"
            RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
        if(expected AND NOT result EQUAL 0 OR NOT expected AND result EQUAL 0)
            message(FATAL_ERROR "Unexpected ${mode} check result: ${result} ${output} ${error}")
        endif()
    endforeach()
endfunction()
# Construct both states independently of the real tree's current release state.
file(READ "${root}/docs/releases/v0.3.2.md" notes)
string(REGEX REPLACE "^#[^\r\n]+" "# ToolX v0.3.2 Release Candidate" notes "${notes}")
string(REGEX REPLACE "> Status:[^\r\n]+" "> Status: Candidate; not yet tagged" notes "${notes}")
file(WRITE "${root}/docs/releases/v0.3.2.md" "${notes}")
file(WRITE "${root}/CHANGELOG.md" "# Changelog\n## [Unreleased]\nTarget: `v0.3.2` release candidate\n")
file(APPEND "${root}/README.md" "\nThis snapshot is the v0.3.2 release candidate.\n")
check(TRUE FALSE)
file(READ "${root}/docs/releases/v0.3.2.md" notes)
string(REPLACE "# ToolX v0.3.2 Release Candidate" "# ToolX v0.3.2" notes "${notes}")
string(REPLACE "Status: Candidate; not yet tagged" "Status: Released" notes "${notes}")
file(WRITE "${root}/docs/releases/v0.3.2.md" "${notes}")
check(FALSE FALSE)
file(READ "${root}/README.md" readme)
string(REPLACE "release candidate" "release" readme "${readme}")
string(REPLACE "release-candidate" "release" readme "${readme}")
file(WRITE "${root}/README.md" "${readme}")
file(READ "${root}/CHANGELOG.md" changelog)
string(REPLACE "## [Unreleased]" "## [0.3.2] - 2026-09-06" changelog "${changelog}")
file(WRITE "${root}/CHANGELOG.md" "${changelog}")
check(TRUE TRUE)
string(REPLACE "Status: Released" "Status: Unknown" notes "${notes}")
file(WRITE "${root}/docs/releases/v0.3.2.md" "${notes}")
check(FALSE FALSE)
