cmake_minimum_required(VERSION 3.20)
if(NOT DEFINED TOOLX_SOURCE_ROOT)
    get_filename_component(TOOLX_SOURCE_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()
if(NOT DEFINED TOOLX_RELEASE_TAG)
    set(TOOLX_RELEASE_TAG "$ENV{GITHUB_REF_NAME}")
endif()
if(NOT TOOLX_RELEASE_TAG MATCHES "^v(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)$")
    message(FATAL_ERROR "Release tag must be vMAJOR.MINOR.PATCH")
endif()
file(READ "${TOOLX_SOURCE_ROOT}/CMakeLists.txt" project_text)
string(REGEX MATCH "project\\(ToolX VERSION ([0-9]+\\.[0-9]+\\.[0-9]+)" matched "${project_text}")
if(NOT matched OR NOT TOOLX_RELEASE_TAG STREQUAL "v${CMAKE_MATCH_1}")
    message(FATAL_ERROR "Release tag does not match the CMake project version")
endif()
set(notes "${TOOLX_SOURCE_ROOT}/docs/releases/${TOOLX_RELEASE_TAG}.md")
if(NOT EXISTS "${notes}")
    message(FATAL_ERROR "Missing version-specific release notes: ${notes}")
endif()
file(READ "${notes}" notes_text)
string(REGEX MATCH "^# ToolX (v[0-9]+[.][0-9]+[.][0-9]+)([\r\n]|$)" heading "${notes_text}")
if(NOT heading OR NOT CMAKE_MATCH_1 STREQUAL TOOLX_RELEASE_TAG)
    message(FATAL_ERROR "Release note heading does not match the tag")
endif()
string(REGEX MATCH "(^|[\r\n])> Status: Released([\r\n]|$)" released "${notes_text}")
if(NOT released)
    message(FATAL_ERROR "Release notes must have Status: Released; candidate notes cannot be published")
endif()
string(REGEX MATCH "Applies to:[^\r\n]*" applies "${notes_text}")
string(REGEX MATCH "v[0-9]+[.][0-9]+[.][0-9]+" applies_version "${applies}")
if(NOT applies_version STREQUAL TOOLX_RELEASE_TAG)
    message(FATAL_ERROR "Release note metadata does not match the tag")
endif()
file(READ "${TOOLX_SOURCE_ROOT}/CHANGELOG.md" changelog)
string(SUBSTRING "${TOOLX_RELEASE_TAG}" 1 -1 release_version)
string(REPLACE "." "[.]" version_pattern "${release_version}")
string(REGEX MATCH "(^|[\r\n])## \\[${version_pattern}\\]([ \r\n]|$)" change_heading "${changelog}")
if(NOT change_heading)
    message(FATAL_ERROR "CHANGELOG must contain an exact ## [${release_version}] release heading")
endif()
message(STATUS "Release preflight passed for ${TOOLX_RELEASE_TAG}")
