cmake_minimum_required(VERSION 3.20)
get_filename_component(source "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(root "${CMAKE_CURRENT_BINARY_DIR}/release-docs-fixture")
file(MAKE_DIRECTORY "${root}")
foreach(item IN ITEMS docs examples include src tools tests cmake .github README.md README.dev.md CHANGELOG.md CMakeLists.txt CMakePresets.json LICENSE)
    file(COPY "${source}/${item}" DESTINATION "${root}")
endforeach()
function(check docs_expected release_expected label)
    foreach(mode IN ITEMS docs release)
        if(mode STREQUAL "docs")
            set(script docs_check.cmake)
            set(expected "${docs_expected}")
        else()
            set(script release_preflight.cmake)
            set(expected "${release_expected}")
        endif()
        execute_process(COMMAND "${CMAKE_COMMAND}" "-DTOOLX_REPOSITORY_ROOT=${root}"
            "-DTOOLX_SOURCE_ROOT=${root}" "-DTOOLX_RELEASE_TAG=v0.3.2"
            -P "${CMAKE_CURRENT_LIST_DIR}/${script}"
            RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
        if(expected AND NOT result EQUAL 0 OR NOT expected AND result EQUAL 0)
            message(FATAL_ERROR "${label}: unexpected ${mode} check result: ${result} ${output} ${error}")
        endif()
    endforeach()
endfunction()
# Construct candidate and released states independently of the actual tree state.
file(READ "${root}/README.md" original_readme)
file(READ "${root}/docs/releases/v0.3.2.md" notes)
string(REGEX REPLACE "^#[^\r\n]+" "# ToolX v0.3.2 Release Candidate" notes "${notes}")
string(REGEX REPLACE "> Status:[^\r\n]+" "> Status: Candidate; not yet tagged" notes "${notes}")
file(WRITE "${root}/docs/releases/v0.3.2.md" "${notes}")
file(WRITE "${root}/CHANGELOG.md" "# Changelog\n## [Unreleased]\nTarget: `v0.3.2` release candidate\n")
file(APPEND "${root}/README.md" "\nThis snapshot is the v0.3.2 release candidate.\n")
check(TRUE FALSE "complete candidate")

# Replace the entire status block, not individual words inside candidate prose.
string(REGEX REPLACE "\n> [*][*]Repository status:[^\n]*(\n>[^\n]*)*" "" released_readme "${original_readme}")
# Also remove metadata if the real tree is already released when this test runs.
string(REGEX REPLACE "\n> (Status|Applies to|Latest release):[^\n]*" "" released_readme "${released_readme}")
string(REPLACE "## What changed in the `v0.3.2` candidate" "## What changed in `v0.3.2`" released_readme "${released_readme}")
string(REPLACE "candidate notes are in" "release notes are in" released_readme "${released_readme}")
string(APPEND released_readme "\n> Status: Released\n> Applies to: v0.3.2\n> Latest release: v0.3.2\n")
set(released_changelog "# Changelog\n\n> Status: Released\n> Applies to: v0.3.2\n\n## [0.3.2] - 2026-09-08\n\nPublished fixes.\n\n## [0.3.1]\n\nThe previous release replaced an unreleased candidate.\n")
set(released_notes "# ToolX v0.3.2\n\n> Audience: ToolX users and release reviewers\n> Status: Released\n> Applies to: v0.3.2\n> Source of truth for: release narrative\n\n## Highlights\n\nPublished fixes.\n\n## Compatibility\n\nNo API changes.\n\n## Build and dependency impact\n\nNo new dependencies.\n\n## Migration\n\nNone.\n\n## Known limitations\n\nSee module documentation.\n")
file(WRITE "${root}/README.md" "${released_readme}")
file(WRITE "${root}/CHANGELOG.md" "${released_changelog}")
file(WRITE "${root}/docs/releases/v0.3.2.md" "${released_notes}")
check(TRUE TRUE "complete released state with historical candidate text")

function(reject_change file text label)
    file(READ "${root}/${file}" saved)
    file(WRITE "${root}/${file}" "${text}")
    check(FALSE FALSE "${file}: ${label}")
    file(WRITE "${root}/${file}" "${saved}")
endfunction()

# Each mutation starts from the valid final state and must fail both entry points.
foreach(file IN ITEMS README.md CHANGELOG.md docs/releases/v0.3.2.md)
    file(READ "${root}/${file}" valid)
    foreach(residue IN ITEMS
            "Target: `v0.3.2` release candidate"
            "candidate release narrative"
            "This note remains a candidate document"
            "This is a RELEASE-CANDIDATE"
            "This release is Unreleased"
            "Not yet tagged"
            "The latest tagged release remains `v0.3.1`.")
        # Insert before the current release heading so changelog history stays out of scope.
        string(REPLACE "> Status: Released" "> Status: Released\n${residue}" invalid "${valid}")
        reject_change("${file}" "${invalid}" "residual status: ${residue}")
    endforeach()
    foreach(field IN ITEMS Status "Applies to")
        string(REGEX REPLACE "> ${field}:[^\n]*\n" "" invalid "${valid}")
        reject_change("${file}" "${invalid}" "missing ${field}")
        string(REPLACE "> ${field}:" "> ${field}: Wrong\n> ${field}:" invalid "${valid}")
        reject_change("${file}" "${invalid}" "duplicate conflicting ${field}")
    endforeach()
    string(REPLACE "> Applies to: v0.3.2" "> Applies to: v0.3.20" invalid "${valid}")
    reject_change("${file}" "${invalid}" "near-match version")
endforeach()
string(REPLACE "> Latest release: v0.3.2" "> Latest release: v0.3.1" invalid "${released_readme}")
reject_change(README.md "${invalid}" "stale latest release")
string(REPLACE "release narrative" "candidate release narrative" invalid "${released_notes}")
reject_change(docs/releases/v0.3.2.md "${invalid}" "candidate narrative metadata")
string(REPLACE "> Status: Released" "> Status: Unknown" invalid "${released_notes}")
reject_change(docs/releases/v0.3.2.md "${invalid}" "unknown status")
string(REPLACE "## [0.3.2] - 2026-09-08" "## [Unreleased]\n\n## [0.3.2] - 2026-09-08" invalid "${released_changelog}")
reject_change(CHANGELOG.md "${invalid}" "unreleased section before current release")
string(REPLACE "Published fixes." "Target: `v0.3.2` release candidate" invalid "${released_changelog}")
reject_change(CHANGELOG.md "${invalid}" "candidate target inside current section")
foreach(file_field IN ITEMS "README.md|Latest release" "docs/releases/v0.3.2.md|Source of truth for")
    string(REPLACE "|" ";" pair "${file_field}")
    list(GET pair 0 file)
    list(GET pair 1 field)
    file(READ "${root}/${file}" valid)
    string(REGEX REPLACE "> ${field}:[^\n]*\n" "" invalid "${valid}")
    reject_change("${file}" "${invalid}" "missing ${field}")
    string(REPLACE "> ${field}:" "> ${field}: Wrong\n> ${field}:" invalid "${valid}")
    reject_change("${file}" "${invalid}" "duplicate ${field}")
endforeach()
foreach(heading IN ITEMS "## [0.3.2]" "## [Unreleased]" "## Hidden current status")
    string(REPLACE "## [0.3.1]" "${heading}" invalid "${released_changelog}")
    reject_change(CHANGELOG.md "${invalid}" "invalid historical boundary: ${heading}")
endforeach()
check(TRUE TRUE "restored released state")
