cmake_minimum_required(VERSION 3.20)
set(root "${CMAKE_CURRENT_BINARY_DIR}/source-archive-fixtures")
file(MAKE_DIRECTORY "${root}/ToolX-source/docs" "${root}/ToolX-source/examples/product_chain_showcase/fixtures")
file(WRITE "${root}/ToolX-source/docs/build-and-compatibility.md" "build guide")
file(WRITE "${root}/ToolX-source/examples/product_chain_showcase/fixtures/app.log" "fixture")
file(REMOVE_RECURSE "${root}/ToolX-source/reference")
function(check success)
    execute_process(COMMAND "${CMAKE_COMMAND}" -E tar czf "${root}/source.tar.gz" ToolX-source
        WORKING_DIRECTORY "${root}" RESULT_VARIABLE packed)
    if(NOT packed EQUAL 0)
        message(FATAL_ERROR "Cannot create archive fixture")
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DTOOLX_SOURCE_ARCHIVE=${root}/source.tar.gz"
        -P "${CMAKE_CURRENT_LIST_DIR}/source_archive_check.cmake"
        RESULT_VARIABLE result OUTPUT_QUIET ERROR_QUIET)
    if(success AND NOT result EQUAL 0)
        message(FATAL_ERROR "Archive checker rejected source docs/log fixtures")
    elseif(NOT success AND result EQUAL 0)
        message(FATAL_ERROR "Archive checker accepted local reference files")
    endif()
endfunction()
check(TRUE)
file(MAKE_DIRECTORY "${root}/ToolX-source/reference")
file(WRITE "${root}/ToolX-source/reference/local.txt" "must not ship")
check(FALSE)
