cmake_minimum_required(VERSION 3.20)
if(NOT EXISTS "${TOOLX_PACK_EXE}")
    message(FATAL_ERROR "TOOLX_PACK_EXE must exist")
endif()
set(root "${CMAKE_CURRENT_BINARY_DIR}/pack-security-contracts")
# Repeated runs must exercise exactly the same fixture.
file(REMOVE_RECURSE "${root}")
file(MAKE_DIRECTORY "${root}/src/report.old.tmp.assets")
file(WRITE "${root}/src/report.old.tmp.assets/keep.txt" "directory sentinel")
foreach(name IN ITEMS "report.old.tmp.txt" "report.new.tmp.txt" "report.removed.tmp.txt")
    file(WRITE "${root}/src/${name}" "legitimate artifact")
endforeach()
execute_process(COMMAND "${TOOLX_PACK_EXE}" stage --src "${root}/src" --out "${root}/stage" --json
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "stage failed: ${output} ${error}")
endif()
foreach(name IN ITEMS "report.old.tmp.txt" "report.new.tmp.txt" "report.removed.tmp.txt" "report.old.tmp.assets/keep.txt")
    if(NOT EXISTS "${root}/stage/${name}")
        message(FATAL_ERROR "stage silently removed legitimate artifact: ${name}")
    endif()
endforeach()
file(MAKE_DIRECTORY "${root}/empty-src")
file(WRITE "${root}/not-a-directory" "sentinel")
execute_process(COMMAND "${TOOLX_PACK_EXE}" plan --src "${root}/empty-src" --out "${root}/not-a-directory" --remove-extra --json
    RESULT_VARIABLE result OUTPUT_VARIABLE output)
if(NOT result EQUAL 3 OR NOT output MATCHES "root is not a directory")
    message(FATAL_ERROR "remove-extra accepted a failed directory enumeration: ${output}")
endif()

file(MAKE_DIRECTORY "${root}/outside" "${root}/linked-src" "${root}/linked-stage")
file(WRITE "${root}/outside/sentinel.txt" "outside sentinel")
function(make_link link target)
    if(WIN32)
        file(TO_NATIVE_PATH "${link}" native_link)
        file(TO_NATIVE_PATH "${target}" native_target)
        execute_process(COMMAND cmd /c mklink /J "${native_link}" "${native_target}"
            RESULT_VARIABLE result OUTPUT_QUIET ERROR_VARIABLE error)
    else()
        execute_process(COMMAND "${CMAKE_COMMAND}" -E create_symlink "${target}" "${link}"
            RESULT_VARIABLE result ERROR_VARIABLE error)
    endif()
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Cannot create boundary test link: ${error}")
    endif()
endfunction()
make_link("${root}/linked-src/link" "${root}/outside")
execute_process(COMMAND "${TOOLX_PACK_EXE}" plan --src "${root}/linked-src" --out "${root}/linked-stage" --include link --json
    RESULT_VARIABLE result OUTPUT_VARIABLE output)
if(result EQUAL 0)
    message(FATAL_ERROR "Explicit include followed an external directory link: ${output}")
endif()
make_link("${root}/linked-stage/report.old.tmp.assets" "${root}/outside")
execute_process(COMMAND "${TOOLX_PACK_EXE}" stage --src "${root}/src" --out "${root}/linked-stage" --json
    RESULT_VARIABLE result OUTPUT_VARIABLE output)
if(result EQUAL 0)
    message(FATAL_ERROR "Stage accepted a destination directory link: ${output}")
endif()
file(READ "${root}/outside/sentinel.txt" sentinel)
if(NOT sentinel STREQUAL "outside sentinel" OR EXISTS "${root}/outside/keep.txt")
    message(FATAL_ERROR "Boundary test changed data outside the stage")
endif()

# Both type transitions must retain the new file and source contents.
file(MAKE_DIRECTORY "${root}/types-src/dir" "${root}/types-stage/file")
file(WRITE "${root}/types-src/file" "new file")
file(WRITE "${root}/types-src/dir/child" "new child")
file(WRITE "${root}/types-stage/file/old" "old child")
file(WRITE "${root}/types-stage/dir" "old file")
execute_process(COMMAND "${TOOLX_PACK_EXE}" plan --src "${root}/types-src" --out "${root}/types-stage" --remove-extra --json
    RESULT_VARIABLE result OUTPUT_VARIABLE output)
if(NOT result EQUAL 0 OR NOT IS_DIRECTORY "${root}/types-stage/file" OR IS_DIRECTORY "${root}/types-stage/dir")
    message(FATAL_ERROR "planning changed stage or rejected valid transitions: ${output}")
endif()
file(READ "${root}/types-stage/file/old" old_child)
file(READ "${root}/types-stage/dir" old_file)
if(NOT old_child STREQUAL "old child" OR NOT old_file STREQUAL "old file")
    message(FATAL_ERROR "planning modified existing contents")
endif()
execute_process(COMMAND "${TOOLX_PACK_EXE}" stage --src "${root}/types-src" --out "${root}/types-stage" --remove-extra --json
    RESULT_VARIABLE result OUTPUT_VARIABLE output)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "type transition failed: ${output}")
endif()
foreach(name IN ITEMS file dir/child)
    file(READ "${root}/types-src/${name}" expected)
    file(READ "${root}/types-stage/${name}" actual)
    if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "type transition lost ${name}")
    endif()
endforeach()

# Reject aliases as well as equal/ancestor/descendant roots before any mutation.
file(MAKE_DIRECTORY "${root}/overlap/src")
file(WRITE "${root}/overlap/src/keep" "source sentinel")
make_link("${root}/overlap-alias" "${root}/overlap")
foreach(pair IN ITEMS "overlap/src|overlap" "overlap|overlap/src" "overlap/src|overlap/src/." "overlap/src|overlap-alias")
    string(REPLACE "|" ";" paths "${pair}")
    list(GET paths 0 source)
    list(GET paths 1 stage)
    execute_process(COMMAND "${TOOLX_PACK_EXE}" stage --src "${root}/${source}" --out "${root}/${stage}" --remove-extra --json
        RESULT_VARIABLE result OUTPUT_VARIABLE output)
    if(NOT result EQUAL 3 OR NOT output MATCHES "roots must not overlap")
        message(FATAL_ERROR "overlapping roots accepted: ${pair}: ${output}")
    endif()
    file(READ "${root}/overlap/src/keep" sentinel)
    if(NOT sentinel STREQUAL "source sentinel")
        message(FATAL_ERROR "overlap changed source")
    endif()
endforeach()

if(NOT WIN32)
    file(MAKE_DIRECTORY "${root}/posix-src")
    foreach(name IN ITEMS "colon:name" "back\\slash")
        file(WRITE "${root}/posix-src/${name}" "${name}")
    endforeach()
    execute_process(COMMAND "${TOOLX_PACK_EXE}" stage --src "${root}/posix-src" --out "${root}/posix-stage" --remove-extra --json
        RESULT_VARIABLE result OUTPUT_VARIABLE output)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "POSIX staging failed: ${output}")
    endif()
    foreach(name IN ITEMS "colon:name" "back\\slash")
        file(READ "${root}/posix-stage/${name}" actual)
        if(NOT actual STREQUAL name)
            message(FATAL_ERROR "POSIX filename changed: ${name}")
        endif()
    endforeach()
endif()

if(NOT WIN32)
    foreach(name IN ITEMS "colon:name" "back\\slash" "C:drive" " leading " "\\leading")
        file(WRITE "${root}/posix-src/${name}" "literal sentinel")
        execute_process(COMMAND "${TOOLX_PACK_EXE}" stage --src "${root}/posix-src" --out "${root}/explicit-stage" --include "${name}" --remove-extra --json
            RESULT_VARIABLE result OUTPUT_VARIABLE output)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Explicit POSIX include rejected ${name}: ${output}")
        endif()
        file(READ "${root}/explicit-stage/${name}" actual)
        if(NOT actual STREQUAL "literal sentinel")
            message(FATAL_ERROR "Explicit POSIX include changed filename: ${name}")
        endif()
        execute_process(COMMAND "${TOOLX_PACK_EXE}" stage --src "${root}/posix-src" --out "${root}/explicit-stage" --include "${name}" --exclude "${name}" --remove-extra --json
            RESULT_VARIABLE result OUTPUT_VARIABLE output)
        if(NOT result EQUAL 0 OR EXISTS "${root}/explicit-stage/${name}")
            message(FATAL_ERROR "Explicit POSIX exclude did not match ${name}: ${output}")
        endif()
    endforeach()
endif()
