cmake_minimum_required(VERSION 3.20)
if(NOT EXISTS "${TOOLX_PACK_EXE}")
    message(FATAL_ERROR "TOOLX_PACK_EXE must exist")
endif()
set(root "${CMAKE_CURRENT_BINARY_DIR}/pack-security-contracts")
# Repeated runs must exercise exactly the same fixture.
file(REMOVE_RECURSE "${root}")
file(MAKE_DIRECTORY "${root}/src/report.old.tmp.assets")
file(WRITE "${root}/src/report.old.tmp.assets/keep.txt" "directory sentinel")
foreach(name IN ITEMS "report.old.tmp.txt" "report.new.tmp.txt" "report.removed.tmp.txt")
    file(WRITE "${root}/src/${name}" "legitimate artifact")
endforeach()
execute_process(COMMAND "${TOOLX_PACK_EXE}" stage --src "${root}/src" --out "${root}/stage" --json
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "stage failed: ${output} ${error}")
endif()
foreach(name IN ITEMS "report.old.tmp.txt" "report.new.tmp.txt" "report.removed.tmp.txt" "report.old.tmp.assets/keep.txt")
    if(NOT EXISTS "${root}/stage/${name}")
        message(FATAL_ERROR "stage silently removed legitimate artifact: ${name}")
    endif()
endforeach()
file(WRITE "${root}/not-a-directory" "sentinel")
execute_process(COMMAND "${TOOLX_PACK_EXE}" plan --src "${root}/src" --out "${root}/not-a-directory" --remove-extra --json
    RESULT_VARIABLE result OUTPUT_VARIABLE output)
if(result EQUAL 0)
    message(FATAL_ERROR "remove-extra accepted a failed directory enumeration: ${output}")
endif()

file(MAKE_DIRECTORY "${root}/outside" "${root}/linked-src" "${root}/linked-stage")
file(WRITE "${root}/outside/sentinel.txt" "outside sentinel")
function(make_link link target)
    if(WIN32)
        file(TO_NATIVE_PATH "${link}" native_link)
        file(TO_NATIVE_PATH "${target}" native_target)
        execute_process(COMMAND cmd /c mklink /J "${native_link}" "${native_target}"
            RESULT_VARIABLE result OUTPUT_QUIET ERROR_VARIABLE error)
    else()
        execute_process(COMMAND "${CMAKE_COMMAND}" -E create_symlink "${target}" "${link}"
            RESULT_VARIABLE result ERROR_VARIABLE error)
    endif()
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Cannot create boundary test link: ${error}")
    endif()
endfunction()
make_link("${root}/linked-src/link" "${root}/outside")
execute_process(COMMAND "${TOOLX_PACK_EXE}" plan --src "${root}/linked-src" --out "${root}/linked-stage" --include link --json
    RESULT_VARIABLE result OUTPUT_VARIABLE output)
if(result EQUAL 0)
    message(FATAL_ERROR "Explicit include followed an external directory link: ${output}")
endif()
make_link("${root}/linked-stage/report.old.tmp.assets" "${root}/outside")
execute_process(COMMAND "${TOOLX_PACK_EXE}" stage --src "${root}/src" --out "${root}/linked-stage" --json
    RESULT_VARIABLE result OUTPUT_VARIABLE output)
if(result EQUAL 0)
    message(FATAL_ERROR "Stage accepted a destination directory link: ${output}")
endif()
file(READ "${root}/outside/sentinel.txt" sentinel)
if(NOT sentinel STREQUAL "outside sentinel" OR EXISTS "${root}/outside/keep.txt")
    message(FATAL_ERROR "Boundary test changed data outside the stage")
endif()
